### ISSUE TITLE
GitHub endpoint for listing repositories

### ISSUE THREAD

**Issue by marceloavf** [marceloavf/github-tools-vsts#19]
Listing repositories from endpoint have some changes and I can't find any documentation about this.
Created an issue on [Developer Community for VSTS](https://developercommunity.visualstudio.com/content/problem/218095/github-connection-endpoint-stop-working-some-days.html) to found the source of the issue.
For now, the work around is to set the repository inside package.json, if you have already set a repostory there is not change, since it already get the name of it.

![image](https://user-images.githubusercontent.com/5435657/37610834-73ff0606-2b7f-11e8-8fae-a5a4d8a30489.png)

**Comment by marceloavf** [comment]
Tried to fix with commit https://github.com/marceloavf/github-tools-vsts/commit/4a38f06b05cb85597db00c6adfdb47a20c891225 - Not result

**Comment by FutureGUIs** [comment]
Seeing the same thing, even putting the repo url in the package.json didn't work and gives this error:
Error: missing required options: repo, owner

**Comment by marceloavf** [comment]
@FutureGUIs have you tried to specify the Manifest JSON in the configuration?
Can you share part of your **package.json** file that has the url ?

**Comment by FutureGUIs** [comment]
can't share the exact url because it's private but it's similar to this:

`  "repository": {
    "url": "https://github.com/xxx/xxx.git"
  }`

and I tried without the `.git` extension in the url.  And just for extra info my github account is an owner of the repo.

**Comment by marceloavf** [comment]
Strange, have you set the package.json in here ?
![image](https://user-images.githubusercontent.com/5435657/37618020-84414ec0-2b93-11e8-972f-1d9fe77a7fce.png)

**Comment by FutureGUIs** [comment]
I didn't know those were the same thing.  But when I hit the ellipsis button there, the popup which looks to be trying to connect to my repo just sits there 'loading' which I guess all goes back to not loading the list of repo's in the first place.

**Comment by marceloavf** [comment]
It should open this window to you select the package.json
![image](https://user-images.githubusercontent.com/5435657/37618841-403c6522-2b96-11e8-8837-f58785106cf6.png)

Seems that VSTS is having some bug in the connection with GitHub, the repositories return is kind unformatted

**Comment by FutureGUIs** [comment]
yeah my dialog doesn't load anything from the repo.  It's gotta be something in VSTS

**Comment by marceloavf** [comment]
@FutureGUIs The problem is just the repo and owner, right?
I'll release a version with input text instead of this pickList, so you can work normally.

**Comment by FutureGUIs** [comment]
well... I just did another build and was able to get it working with the manifest.json pointing to my package.json file, except I got, which I get often which I understand is separate from this issue:

`2018-03-19T20:34:38.9681910Z ##[debug]task result: Failed
2018-03-19T20:34:38.9799290Z ##[error]An error occured, log returned: 
Error: write EPIPE
2018-03-19T20:34:38.9845150Z ##[debug]Processed: ##vso[task.issue type=error;]An error occured, log returned: %0AError: write EPIPE
2018-03-19T20:34:38.9889200Z ##[debug]Processed: ##vso[task.complete result=Failed;]An error occured, log returned: %0AError: write EPIPE`

I do have a VSTS Release separate that I am working with as well though that because of the repo dropdown being empty and the package.json isn't in my release artifacts, it'd still be nice to have a 'text input' field

**Comment by marceloavf** [comment]
I'll work in this text input.

Could you please open another issue with this EPIPE error, seems to be something with the upload function, can also be the version of the node you are using, thanks!

**Comment by marceloavf** [comment]
🙌  Fixed with https://github.com/marceloavf/github-tools-vsts/commit/9cd4d3dec46ec68a7e1800ebcd62dbc5f8c3356a in v0.3.2, should be released soon.

If you still have the problem, try to delete GitHub endpoint and register it again.

**Comment by FutureGUIs** [comment]
yep that fixed the repo dropdown, I'll make another bug for that other issue shortly
